name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a build step (like a static site generator), add it here.
      # For plain HTML/CSS with files at repo root, no build needed.

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./      # folder to publish (root for plain HTML)

          - name: Deploy to GitHub Pages
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions[bot]@users.noreply.github.com"
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
    git checkout gh-pages || git checkout -b gh-pages
    git add .
    git commit -m "Deploy to GitHub Pages"
    git push origin gh-pages
