name: Deploy Website

on:
  push:
    branches:
      - main   # Run on every push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Upload artifact (build output)
      - name: Upload website
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./
